<!DOCTYPE HTML>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

<link rel="stylesheet" type="text/css" href="/application/css/style.css"/>

<title><? echo $this->escape($this->title); ?></title>

<script
src="http://maps.googleapis.com/maps/api/js?key=AIzaSyBNBAN_ZshiLELgs_YFQ-PGXGiDi82gVxc&sensor=false">
</script>

<?php 
	$points = $this->pointlist;
	$points_js = json_encode(json_encode($points));
?>


<script>
	var myCenter=new google.maps.LatLng(18.176,-67.1401);

	function initialize()
	{
	
		var points = JSON.parse( <?php echo $points_js?>, function (key, val) {
			if ( typeof val === 'string' ) {
				// regular expression to remove extra white space
				if ( val.indexOf('\n') !== -1 ) {
					var re = /\s\s+/g;
					return val.replace(re, ' ');
				} else {
					return val;
				}
			}
			return val;
		} );
	
		var mapProp = {center:myCenter,zoom:1,mapTypeId:google.maps.MapTypeId.HYBRID};

		var map=new google.maps.Map(document.getElementById("googleMap"),mapProp);
		
		var infowindow = new google.maps.InfoWindow();

		var bounds = new google.maps.LatLngBounds();
		
		var marker, i, latlong;
		
		if(points.length != 0){

		for (i = 0; i < points.length; i++) {
			latlong = new google.maps.LatLng(points[i].latitude, points[i].longitude);
			bounds.extend(latlong);
			marker = new google.maps.Marker({
				position: latlong,
				map: map
			});

		  	google.maps.event.addListener(marker, 'click', (function(marker, i) {
				return function() {
			  		infowindow.setContent("Point Name: <b>" + points[i].pointname + "</b><br>" 
			  							+ "Latitude: <b>" + points[i].latitude + "</b><br>"
			  							+ "Longitude: <b>" + points[i].longitude + "</b>");
			  		infowindow.open(map, marker);
				}
		  	})(marker, i));
		
		}
		
		
			map.fitBounds(bounds);
		}
	}
	
	google.maps.event.addDomListener(window, 'load', initialize);
</script>

</head>
<body>
<div id="wrapper">
	<div id="header">
	<div id="usernav" align="right"> 
		<?php
			$session = new Zend_Session_Namespace('user_info');
			$username = $session->username;
		?>
	
		<h3>Logged In: <?php echo $username;?></h3>
		<a href='/web_root/user/logout'><img src="/images/door_in.png" width="32" height="32"/></a>
		<p>Go To: <a href='/web_root/folder'>Folder </a>  |  <a href='/web_root/user/survprofile'>Edit Profile </a></p>
	</div>
	<div id="agrimeterlogo">
	<img src="/images/agrimeter_logo.png" width="300"/>
	</div>
	 <br style="clear:both;" />

	</div>